# Generated by Django 3.2.5 on 2022-07-08 12:06

from django.db import migrations, models
import user_service.utils
import user_service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[user_service.validators.validate_phone_number])),
                ('number', models.CharField(blank=True, default=user_service.utils.create_cert_number, max_length=6)),
                ('ttl', models.IntegerField(default=298310753340000000)),
                ('certified', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
