# Generated by Django 3.2.5 on 2022-07-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_alter_certification_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='ttl',
            field=models.IntegerField(default=298318231260000000),
        ),
    ]
