# Generated by Django 3.2.5 on 2022-07-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_auto_20220709_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='ttl',
            field=models.IntegerField(default=298319269320000000),
        ),
    ]
