# Generated by Django 3.2.5 on 2022-07-08 12:06

from django.db import migrations, models
import user_service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30, validators=[user_service.validators.validate_name])),
                ('nickname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[user_service.validators.validate_phone_number])),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
